### ISSUE TITLE
Seemingly unnecessary mounting of the color picker

### ISSUE THREAD

**Issue by lxynox** [Justineo/make-github-greater#2]
Thanks for the great work, i'm learning from it.

As i went through the source code, the mounting of the color picker confused me a bit:

```javascript
document.body.appendChild(picker);
picker.style.cssText = `position: absolute; top: -${picker.offsetHeight}px; left: -${picker.offsetWidth}px;`;
picker.value = current;
```

It's positioned out of viewport(neither visible/interactive) and i removed it from console

```javascript
document.body.removeChild( document.querySelector('input[type=color]') )
```

the extension seems to work as normal, are there any reason to attach it to DOM here?

**Comment by Justineo** [comment]
It seems that you are right. `click` can be triggered when the input is not attached to DOM (at least in latest Chrome). I'll look into this later and the related code can be removed if the attaching & hiding are totally unnecessary.

**Comment by lxynox** [comment]
Just tested, for latest Chrome/Opera, Firefox DE, color picker can be detached from DOM.

However, **Safari 10.1+** needs it to be attached to fire `click` event ; )
